# Generated by Django 4.1 on 2022-08-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shirts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(default='Black', max_length=20)),
                ('type', models.CharField(default='Adult', max_length=50)),
                ('price', models.TextField(default='200')),
                ('stock', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Shirt',
                'verbose_name_plural': 'Shirts',
            },
        ),
        migrations.CreateModel(
            name='Sweaters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(default='Black', max_length=20)),
                ('type', models.CharField(default='Adult', max_length=50)),
                ('price', models.TextField(default='200')),
                ('stock', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Sweater',
                'verbose_name_plural': 'Sweaters',
            },
        ),
    ]
