# Generated by Django 4.1 on 2022-08-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_alter_shirts_name_alter_shirts_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirts',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='sweaters',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
