# Generated by Django 4.1 on 2022-08-18 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0005_alter_shirts_photo_alter_sweaters_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirts',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 9, 39, 7, 396646), verbose_name='date posted'),
        ),
        migrations.AddField(
            model_name='sweaters',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 9, 39, 7, 384316), verbose_name='date posted'),
        ),
    ]
