# Generated by Django 4.1 on 2022-08-18 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0006_shirts_posted_sweaters_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirts',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 9, 51, 36, 648027), verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='sweaters',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 9, 51, 36, 641079), verbose_name='date posted'),
        ),
    ]
