# Generated by Django 4.1 on 2022-08-18 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0007_alter_shirts_posted_alter_sweaters_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirts',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 9, 59, 44, 83596), verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='sweaters',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 9, 59, 44, 83596), verbose_name='date posted'),
        ),
    ]
