# Generated by Django 4.1 on 2022-08-18 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0008_alter_shirts_posted_alter_sweaters_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sweaters',
            options={},
        ),
        migrations.AlterField(
            model_name='shirts',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 10, 1, 22, 753676), verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='sweaters',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 10, 1, 22, 753676), verbose_name='date posted'),
        ),
    ]
