# Generated by Django 4.1 on 2022-08-18 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0009_alter_sweaters_options_alter_shirts_posted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sweaters',
            options={'verbose_name': 'Sweater', 'verbose_name_plural': 'Sweaters'},
        ),
        migrations.AlterField(
            model_name='shirts',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 10, 5, 27, 865156), verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='sweaters',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 10, 5, 27, 865156), verbose_name='date posted'),
        ),
    ]
