# Generated by Django 4.1 on 2022-08-18 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0014_alter_shirts_posted_alter_sweaters_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shirts',
            old_name='color',
            new_name='shirt_color',
        ),
        migrations.RenameField(
            model_name='shirts',
            old_name='name',
            new_name='shirt_name',
        ),
        migrations.RenameField(
            model_name='shirts',
            old_name='photo',
            new_name='shirt_photo',
        ),
        migrations.RenameField(
            model_name='shirts',
            old_name='price',
            new_name='shirt_price',
        ),
        migrations.RenameField(
            model_name='shirts',
            old_name='stock',
            new_name='shirt_stock',
        ),
        migrations.RenameField(
            model_name='shirts',
            old_name='type',
            new_name='shirt_type',
        ),
        migrations.RenameField(
            model_name='sweaters',
            old_name='color',
            new_name='sweater_color',
        ),
        migrations.RenameField(
            model_name='sweaters',
            old_name='name',
            new_name='sweater_name',
        ),
        migrations.RenameField(
            model_name='sweaters',
            old_name='photo',
            new_name='sweater_photo',
        ),
        migrations.RenameField(
            model_name='sweaters',
            old_name='price',
            new_name='sweater_price',
        ),
        migrations.RenameField(
            model_name='sweaters',
            old_name='stock',
            new_name='sweater_stock',
        ),
        migrations.RenameField(
            model_name='sweaters',
            old_name='type',
            new_name='sweater_type',
        ),
        migrations.RemoveField(
            model_name='shirts',
            name='posted',
        ),
        migrations.RemoveField(
            model_name='sweaters',
            name='posted',
        ),
        migrations.AddField(
            model_name='shirts',
            name='shirt_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 10, 22, 51, 400728), verbose_name='date posted'),
        ),
        migrations.AddField(
            model_name='sweaters',
            name='sweater_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 10, 22, 51, 398730), verbose_name='date posted'),
        ),
    ]
