# Generated by Django 4.1 on 2022-08-18 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0015_rename_color_shirts_shirt_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sweaters',
            options={'ordering': ['sweater_price'], 'verbose_name_plural': 'Sweaters'},
        ),
        migrations.AlterField(
            model_name='shirts',
            name='shirt_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 13, 15, 57, 856408), verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='sweaters',
            name='sweater_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 13, 15, 57, 856408), verbose_name='date posted'),
        ),
    ]
