# Generated by Django 4.1 on 2022-08-18 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0016_alter_sweaters_options_alter_shirts_shirt_posted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_name', models.CharField(default='Casual', max_length=20)),
                ('shoe_color', models.CharField(default='Black', max_length=20)),
                ('shoe_type', models.CharField(default='Adult', max_length=50)),
                ('shoe_price', models.CharField(default='200', max_length=200)),
                ('shoe_posted', models.DateTimeField(default=datetime.datetime(2022, 8, 18, 14, 1, 20, 727779), verbose_name='date posted')),
                ('shoe_stock', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, upload_to='Shirts/')),
            ],
            options={
                'verbose_name': 'Shoe',
                'verbose_name_plural': 'Shoes',
            },
        ),
        migrations.RenameField(
            model_name='shirts',
            old_name='shirt_photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='sweaters',
            old_name='sweater_photo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='shirts',
            name='shirt_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 14, 1, 20, 726780), verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='sweaters',
            name='sweater_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 14, 1, 20, 725779), verbose_name='date posted'),
        ),
    ]
