# Generated by Django 4.1 on 2022-08-18 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0017_shoes_rename_shirt_photo_shirts_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirts',
            name='shirt_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 14, 1, 32, 78886), verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='shoe_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 14, 1, 32, 78886), verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='sweaters',
            name='sweater_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 14, 1, 32, 78886), verbose_name='date posted'),
        ),
    ]
