# Generated by Django 4.1 on 2022-08-18 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0019_alter_shirts_shirt_posted_alter_shoes_shoe_posted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='mainview/')),
            ],
        ),
        migrations.AlterField(
            model_name='shirts',
            name='shirt_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 18, 49, 8, 845898), verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='shoe_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 18, 49, 8, 845898), verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='sweaters',
            name='sweater_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 18, 18, 49, 8, 845898), verbose_name='date posted'),
        ),
    ]
