# Generated by Django 4.1 on 2022-08-21 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0025_alter_shirts_shirt_posted_alter_shoes_shoe_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirts',
            name='shirt_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 21, 11, 12, 42, 832909), verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='shoe_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 21, 11, 12, 42, 833909), verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='sweaters',
            name='sweater_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 21, 11, 12, 42, 831909), verbose_name='date posted'),
        ),
    ]
