# Generated by Django 4.1 on 2022-08-22 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0027_alter_shirts_shirt_posted_alter_shoes_shoe_posted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fashion_Shirts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_name', models.CharField(default='Casual', max_length=20)),
                ('shirt_color', models.CharField(default='Black', max_length=20)),
                ('shirt_type', models.CharField(default='Adult', max_length=50)),
                ('shirt_price', models.CharField(default='200', max_length=200)),
                ('shirt_posted', models.DateTimeField(default=datetime.datetime(2022, 8, 22, 7, 30, 26, 281629), verbose_name='date posted')),
                ('shirt_stock', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, upload_to='Shirts/')),
            ],
            options={
                'verbose_name': 'Shirt',
                'verbose_name_plural': 'Shirts',
            },
        ),
        migrations.CreateModel(
            name='Fashion_Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_name', models.CharField(default='Casual', max_length=20)),
                ('shoe_color', models.CharField(default='Black', max_length=20)),
                ('shoe_type', models.CharField(default='Adult', max_length=50)),
                ('shoe_price', models.CharField(default='200', max_length=200)),
                ('shoe_posted', models.DateTimeField(default=datetime.datetime(2022, 8, 22, 7, 30, 26, 297581), verbose_name='date posted')),
                ('shoe_stock', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, upload_to='Shirts/')),
            ],
            options={
                'verbose_name': 'Shoe',
                'verbose_name_plural': 'Shoes',
            },
        ),
        migrations.CreateModel(
            name='Fashion_Sweaters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sweater_name', models.CharField(default='Casual', max_length=20)),
                ('sweater_color', models.CharField(default='Black', max_length=20)),
                ('sweater_type', models.CharField(default='Adult', max_length=50)),
                ('sweater_price', models.TextField(default='200', max_length=200)),
                ('sweater_posted', models.DateTimeField(default=datetime.datetime(2022, 8, 22, 7, 30, 26, 281629), verbose_name='date posted')),
                ('sweater_stock', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, upload_to='Sweater/')),
            ],
            options={
                'verbose_name_plural': 'Sweaters',
                'ordering': ['sweater_price'],
            },
        ),
        migrations.DeleteModel(
            name='Shirts',
        ),
        migrations.DeleteModel(
            name='Shoes',
        ),
        migrations.DeleteModel(
            name='Sweaters',
        ),
    ]
