# Generated by Django 4.1 on 2022-08-22 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0028_fashion_shirts_fashion_shoes_fashion_sweaters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electronic_type', models.CharField(default='TV', max_length=20)),
                ('electronic_name', models.CharField(default='HD Bravia TV', max_length=20)),
                ('electronic_brand', models.CharField(default='Sony', max_length=20)),
                ('electronic_size', models.IntegerField(default=32)),
                ('electronic_price', models.IntegerField(default=10000)),
                ('electronic_weight', models.IntegerField(default=4)),
            ],
        ),
        migrations.AlterModelOptions(
            name='fashion_shirts',
            options={'verbose_name_plural': 'Fashion shirts'},
        ),
        migrations.AlterModelOptions(
            name='fashion_shoes',
            options={'verbose_name_plural': 'Fashion shoes'},
        ),
        migrations.AlterModelOptions(
            name='fashion_sweaters',
            options={'verbose_name_plural': 'Fashion sweaters'},
        ),
        migrations.AlterModelOptions(
            name='mainview',
            options={'verbose_name_plural': 'Mainview'},
        ),
        migrations.AlterField(
            model_name='fashion_shirts',
            name='shirt_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 8, 19, 40, 986358), verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='fashion_shoes',
            name='shoe_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 8, 19, 41, 1984), verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='fashion_sweaters',
            name='sweater_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 8, 19, 40, 986358), verbose_name='date posted'),
        ),
    ]
