# Generated by Django 4.1 on 2022-08-22 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0029_electronics_alter_fashion_shirts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashion_shirts',
            name='shirt_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 8, 20, 57, 143846), verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='fashion_shoes',
            name='shoe_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 8, 20, 57, 143846), verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='fashion_sweaters',
            name='sweater_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 8, 20, 57, 143846), verbose_name='date posted'),
        ),
    ]
