# Generated by Django 4.1 on 2022-08-22 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0030_alter_fashion_shirts_shirt_posted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electronics',
            options={'verbose_name_plural': 'Electronics'},
        ),
        migrations.AddField(
            model_name='electronics',
            name='electronic_rating',
            field=models.IntegerField(default=1, max_length=5),
        ),
        migrations.AddField(
            model_name='fashion_shirts',
            name='shirt_rating',
            field=models.IntegerField(default=1, max_length=5),
        ),
        migrations.AddField(
            model_name='fashion_shoes',
            name='shoe_rating',
            field=models.IntegerField(default=1, max_length=5),
        ),
        migrations.AddField(
            model_name='fashion_sweaters',
            name='sweater_rating',
            field=models.IntegerField(default=1, max_length=5),
        ),
        migrations.AlterField(
            model_name='fashion_shirts',
            name='shirt_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 8, 40, 5, 156837), verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='fashion_shoes',
            name='shoe_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 8, 40, 5, 156837), verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='fashion_sweaters',
            name='sweater_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 8, 40, 5, 156837), verbose_name='date posted'),
        ),
    ]
