# Generated by Django 4.1 on 2022-08-22 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0031_alter_electronics_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronics',
            name='electronic_image',
            field=models.ImageField(blank='True', upload_to='Electronics/'),
        ),
        migrations.AlterField(
            model_name='electronics',
            name='electronic_rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fashion_shirts',
            name='shirt_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 8, 42, 8, 653608), verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='fashion_shirts',
            name='shirt_rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fashion_shoes',
            name='shoe_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 8, 42, 8, 654607), verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='fashion_shoes',
            name='shoe_rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fashion_sweaters',
            name='sweater_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 8, 42, 8, 653608), verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='fashion_sweaters',
            name='sweater_rating',
            field=models.IntegerField(default=1),
        ),
    ]
