# Generated by Django 4.1 on 2022-08-22 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0032_electronics_electronic_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fashion_type', models.CharField(default='Adult', max_length=50)),
                ('fashion_name', models.CharField(default='Casual', max_length=20)),
                ('fashion_color', models.CharField(default='Black', max_length=20)),
                ('fashion_price', models.TextField(default='200', max_length=200)),
                ('fashion_posted', models.DateTimeField(default=datetime.datetime(2022, 8, 22, 9, 0, 16, 963363), verbose_name='date posted')),
                ('fashion_stock', models.IntegerField(default=1)),
                ('fashion_rating', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, upload_to='Sweater/')),
            ],
            options={
                'verbose_name_plural': 'Fashion',
            },
        ),
        migrations.DeleteModel(
            name='Fashion_Shirts',
        ),
        migrations.DeleteModel(
            name='Fashion_Shoes',
        ),
        migrations.DeleteModel(
            name='Fashion_Sweaters',
        ),
        migrations.RenameField(
            model_name='electronics',
            old_name='electronic_image',
            new_name='image',
        ),
    ]
