# Generated by Django 4.1 on 2022-08-22 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0033_fashion_delete_fashion_shirts_delete_fashion_shoes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electronics',
            old_name='electronic_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='fashion',
            old_name='fashion_rating',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='fashion',
            name='fashion_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 9, 4, 0, 531896), verbose_name='date posted'),
        ),
    ]
