# Generated by Django 4.1 on 2022-08-22 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0034_rename_electronic_rating_electronics_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashion',
            name='fashion_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 9, 4, 38, 828824), verbose_name='date posted'),
        ),
    ]
