# Generated by Django 4.1 on 2022-08-22 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0035_alter_fashion_fashion_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electronics',
            old_name='electronic_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='electronics',
            old_name='electronic_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='electronics',
            old_name='electronic_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='electronics',
            old_name='electronic_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='electronics',
            old_name='electronic_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='electronics',
            old_name='electronic_weight',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='fashion',
            old_name='fashion_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='fashion',
            old_name='fashion_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='fashion',
            old_name='fashion_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='fashion',
            old_name='fashion_stock',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='fashion',
            old_name='fashion_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='fashion_posted',
        ),
        migrations.AddField(
            model_name='electronics',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 9, 11, 6, 894644), verbose_name='date posted'),
        ),
        migrations.AddField(
            model_name='fashion',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 9, 11, 6, 894644), verbose_name='date posted'),
        ),
    ]
