# Generated by Django 4.1 on 2022-08-22 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0036_rename_electronic_brand_electronics_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronics',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 9, 11, 17, 670274), verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='fashion',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 22, 9, 11, 17, 671277), verbose_name='date posted'),
        ),
    ]
