# Generated by Django 4.1 on 2022-08-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0037_alter_electronics_posted_alter_fashion_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronics',
            name='posted',
            field=models.DateTimeField(verbose_name='date posted'),
        ),
        migrations.AlterField(
            model_name='fashion',
            name='posted',
            field=models.DateTimeField(verbose_name='date posted'),
        ),
    ]
