# Generated by Django 4.1 on 2022-08-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0038_alter_electronics_posted_alter_fashion_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashion',
            name='price',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='fashion',
            name='type',
            field=models.CharField(default='Shirt', max_length=50),
        ),
    ]
