# Generated by Django 4.1 on 2022-08-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0039_alter_fashion_price_alter_fashion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronics',
            name='category',
            field=models.CharField(default='TV', max_length=20),
        ),
        migrations.AddField(
            model_name='fashion',
            name='category',
            field=models.CharField(default='Shirt', max_length=20),
        ),
    ]
