# Generated by Django 4.1 on 2022-08-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0040_electronics_category_fashion_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronics',
            name='price_text',
            field=models.CharField(default='10,000', max_length=100),
        ),
        migrations.AlterField(
            model_name='electronics',
            name='name',
            field=models.CharField(default='HD Bravia', max_length=20),
        ),
    ]
