# Generated by Django 4.1 on 2022-08-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0041_electronics_price_text_alter_electronics_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronics',
            name='condition',
            field=models.CharField(default='Brand New', max_length=100),
        ),
    ]
