# Generated by Django 4.1 on 2022-08-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0042_electronics_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashion',
            name='condition',
            field=models.CharField(default='Brand New', max_length=100),
        ),
    ]
