# Generated by Django 4.1 on 2022-08-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0043_fashion_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashion',
            name='price_text',
            field=models.CharField(default='500', max_length=100),
        ),
    ]
