# Generated by Django 4.1 on 2022-08-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0044_fashion_price_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashion',
            name='type',
        ),
    ]
