# Generated by Django 4.1 on 2022-08-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0045_remove_fashion_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronics',
            name='type',
        ),
        migrations.AlterField(
            model_name='fashion',
            name='category',
            field=models.SlugField(default='shirt', max_length=20),
        ),
    ]
